name: kosanku_mobile
description: Kosanku auth demo with Laravel API
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0
  flutter_secure_storage: ^9.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  bot_toast: ^4.1.3
  flutter_login: ^5.0.0
  url_launcher: ^6.3.0
  local_auth: ^2.3.0
  device_info_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_native_splash:
  color: "#00BCD4"            # cyan
  image: assets/logo.png      # opsional: logo PNG transparan
  android_12:
    color: "#00BCD4"
    image: assets/logo.png
  android: true
  ios: true
